### ISSUE TITLE
Add support for more .hsf files from Mario Party 5

### ISSUE THREAD

**Issue by ghost** [Ploaj/Metanoia#3]
Hi,

As i described in a message after you closed the previous issue thread i created before, even with your update, your program still can't seem to fully recognise some textures from certain models and, in other cases, it can't even open some of them.

But no worries, i don't wanna you fully support every Mario Party 5 .bin, but yes for the following bin files: sd00.bin, sdd1.bin and sdroom.bin.

To be honest and if i could ask you, please, focus more on hsf files from sd00.bin, since i wanna their models and their respective textures.

If you need direct access, go for sd00 folder from here: https://onedrive.live.com/?authkey=%21AHM8pnAzPGtlqr0&id=EF754F1B0B292B09%2121265&cid=EF754F1B0B292B09

Thanks! =]

**Comment by Ploaj** [comment]
Okay, I added a bunch of the missing texture formats and adjusted some other stuff so more of the files open.

I'll leave this open until you confirm they open correctly.

**Comment by ghost** [comment]
Hi,

More feedback:

From sd00:

sd00_file65.hsf, sd00_file66.hsf, sd00_file67.hsf, sd00_file73.hsf couldn't be loaded;

sd00_file68.hsf: when exported, g027m2.png texture is wrong;

sd00_file70's texture is wrong: when viewed via your program or via blender, it's just an white ball, instead of being the eye we see in-game: http://prntscr.com/pwir5t , for a comparison: https://www.mariowiki.com/images/a/a6/Eye_gun.png

sd00_file74.hsf is partially correctly loaded, but it shows that big green box instead of bowser's arm: http://prntscr.com/pwion7 , for a comparison: https://www.mariowiki.com/images/5/55/Bowser_punch.png

sd00_file75.hsf's texture is wrong: viewing via your program or via blender isn't showing correctly: http://prntscr.com/pwjoi0 , for comparison: https://www.mariowiki.com/images/e/ec/Bobomb_wall.png

From sdroom:

sdroom_file9.hsf: when exported, g002m201.png texture is wrong;

sdroom_file11: when exported, shupokemuri00.png texture is wrong;

sdroom_file13: when exported, g002m201.png texture is wrong;

sdroom_file15: when exported, CI8oya_e00.png texture is wrong;

sdroom_file16: some textures may be missing: http://prntscr.com/pwjvz9, to compare (with Dolphin's help): http://prntscr.com/pwjwkc - maybe Dolphin is ripping textures from other models, who knows?

I'll wait for when the next update comes out to see if those reported errors were fixed.

If not already, you can download those reported hsf files from here: https://1drv.ms/u/s!AgkrKQsbT3XvgaYRczymcDM8a2WqvQ?e=yhvL8g

I used Dolphin to check if all textures were correctly dumped or not.

And that's it! =]

**Comment by Ploaj** [comment]
Fixed file65, file66, file67, and file75

Fixed the various texture issues
sdroom_file9, file73, sdroom_file11, sdroom_file13, and sdroom_file15

I'm not sure about sdroom_file16. It doesn't seem to be missing any in the file.

sd00_file70 
The textures are fine. The outer sphere is meant to have transparency which is not shown in the viewer or blender.

sd00_file74
Bowser's arm is there behind the box. The box mesh is called "atari2".

**Comment by ghost** [comment]
Hello,

About all your explanation: understood, that is nice to know!

Dude, i must say: thanks A TON for all this your work! What an awesome tool! Thanks to all this, i could grab everything i wanted from Mario Party 5 (at least for now, hehe).

Let's keep contact via discord: Machow8#7736 : add me there, hehe. I see you there!

Once again, thanks! =D
